apiVersion: v1
kind: Service
metadata:
  name: test-service
  labels:
    app: test-service
spec:
  selector:
    app: test-pod
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 80
  type: ClusterIP
